name: Racket CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        racket-version: [ '6.12', '7.0', '7.4', '7.5', '7.6', '7.7', '7.8' ]
        racket-variant: [ 'BC' ]
        experimental: [false]
        include:
          - racket-version: '8.0'
            racket-variant: 'CS'
            experimental: true
          - racket-version: '8.1'
            racket-variant: 'CS'
            experimental: true
          - racket-version: 'current'
            racket-variant: 'CS'
            experimental: true
    name: Racket ${{ matrix.racket-version }} ${{ matrix.racket-variant }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.4
        with:
          architecture: 'x64'
          version: ${{ matrix.racket-version }}
          variant: ${{ matrix.racket-variant }}
      - run: raco pkg install --auto -t dir racketscript-compiler/
      - run: make unit-test
      - run: make integration-test
  coverage:
    needs: build
    runs-on: ubuntu-latest
    name: Racket Coverage
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.4
        with:
          architecture: 'x64'
          variant: 'CS'
          version: 'stable'
      - name: Install package and its dependencies
        run: |
          raco pkg install --auto cover https://github.com/vishesh/cover-codecov.git
          raco pkg install --auto -t dir racketscript-compiler/
      - name: Generate coverage report
        run: |
          COVERAGE_MODE=1 raco cover -f codecov -b \
              racketscript-compiler/racketscript/ \
              tests/fixture.rkt
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          name: codecov-racketscript
          fail_ci_if_error: false
          verbose: true
